### ISSUE TITLE
RNA Linear folding feature

### ISSUE THREAD

**Issue by isaacguerreir** [Lattice-Automation/seqfold#12]
A week later I tried to use seqfold to calculate MFE and secondary structure but it took too much time for an HTTP request through a serverless environment (waiting time is normally limited to 30-60 seconds for performance reasons). My use case was specifically for vaccine RNA sequences, so most of them are greater than 3kbp.

So I used [Linear Fold](https://github.com/LinearFold/LinearFold) by running a bash script to build the project and putting them inside a folder of my project and using some python wrapping to run the command line LinearFold binary and parsing the output. It was much faster and 

I think I can do a better job by really taking the `BeamCKYParser` function and wrapping using some lib like CPython, however, it will take some time.

What do you think?

**Comment by jjtimmons** [comment]
Wow LinearFold is dope. Seems really impressive, esp since the folding accuracy is still pretty good re: https://academic.oup.com/bioinformatics/article/35/14/i295/5529205

I think that sounds like a pretty good idea though and that folks will benefit from it. I don't think that `seqfold` is the repo for it though

If the LinearFold folks are responsive I think maybe that repo. Could add a repo with multiple client interfaces, Python being one of which? Or make a new one like `LinearFold-py`. I'm thinking of this primer3-py tool I used in the past that was helpful: https://github.com/libnano/primer3-py/tree/master/primer3

**Comment by jjtimmons** [comment]
Closing in this repo @isaacguerreir but lmk how it goes. Seems great
